export const Resgister_user="Register_User"
export const Login_user="Login_User"
export const Load_user="Load_User"
export const Login_controler="Login_controler"
export const Logout_controler="Logout_controler"
export const Alert_controler_success="Alert_controler_success"
export const Alert_controler_error="Alert_controler_error"
